src/main/docker/Dockerfile, src/main/docker/server.xslt
https://portal.digitalsafe.net/browse/SCMOD-8297
=> SCMOD-8297: Don't expose internal details on errors

src/main/docker/Dockerfile
This will be reverted immediately after the release.
=> SCMOD-9120 removed zypper command

release-notes-2.0.0.md, src/main/docker/Dockerfile
JIRA: https://portal.digitalsafe.net/browse/SCMOD-9768
=> SCMOD-9768: Updated to tomcat 9.0.35

opensuse-tomcat-jre11-image/src/main/docker/Dockerfile
http://sou-jenkins2.swinfra.net/job/CAFapi/job/CAFapi~opensuse-tomcat-jre11-image~master-buildfix~CI/1/console
=> SCMOD-10189: Temporary removal of zypper update to fix build

.gitignore, opensuse-tomcat-jre11-image/src/main/docker/Dockerfile, pom.xml, release-notes-2.2.0.md
https://portal.digitalsafe.net/browse/SCMOD-11070
=> SCMOD-11070: Update tomcat to version 9.0.38

opensuse-tomcat-jre11-image/src/main/docker/Dockerfile
https://portal.digitalsafe.net/browse/SCMOD-13716
=> SCMOD-13716 Updated to use opensuse-jre11 3.4.0 snapshot

opensuse-tomcat-jre11-image/src/main/docker/Dockerfile, pom.xml, release-notes-2.5.0.md
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=396556
=> US396556: Tomcat updated to version 9.0.58

pom.xml
https://internal.almoctane.com/ui/?p=131002/6001#/team-backlog/stories
=> US397426: Migrating logging version

opensuse-tomcat-jre11-image/src/main/docker/logback-access.xml, opensuse-tomcat-jre11-image/src/main/docker/logback.xml
https://internal.almoctane.com/ui/?p=131002%2F6001#/entity-navigation?entityType=work_item&id=408005
=> US408005: Update logging pattern + redirect stdout to stderr

pom.xml
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=580238
=> US580238: Updating commons version

opensuse-tomcat-jre11-juli-image/src/main/docker/Dockerfile, pom.xml, release-notes-2.7.0.md
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=632168
=> D632168: Upgraded tomcat to 9.0.73

release-notes-2.9.2.md
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=778002
=> US778002: Release preparation

opensuse-tomcat-jre11-juli-image/src/main/docker/Dockerfile, pom.xml, release-notes-2.10.0.md
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=788018
=> US788018: Updated to Tomcat 9.0.76

release-notes-2.10.0.md
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=795027
=> US795027: Release preparation

release-notes-2.11.0.md
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=846018
=> US846018: Release preparation

opensuse-tomcat-jre11-juli-image/src/main/docker/Dockerfile, pom.xml, release-notes-2.12.0.md
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=866084
=> US866084: Tomcat updated to version 9.0.83

release-notes-2.12.0.md
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=866069
=> US866069: Release preparation

caf-logging-tomcat-juli/pom.xml, opensuse-tomcat-jre11-image/pom.xml, opensuse-tomcat-jre11-image/src/main/docker/Dockerfile, opensuse-tomcat-jre11-image/src/main/docker/logback-access.xml, opensuse-tomcat-jre11-image/src/main/docker/logback.xml, opensuse-tomcat-jre11-image/src/main/docker/server.xslt, opensuse-tomcat-jre11-image/src/main/docker/setenv.bat, opensuse-tomcat-jre11-image/src/main/docker/setenv.sh, opensuse-tomcat-jre11-image/src/test/resources/test.html, opensuse-tomcat-jre11-juli-image/pom.xml, opensuse-tomcat-jre11-juli-image/src/main/docker/Dockerfile, opensuse-tomcat-jre11-juli-image/src/main/docker/logging.properties, opensuse-tomcat-jre11-juli-image/src/main/docker/server.xslt, opensuse-tomcat-jre11-juli-image/src/main/docker/startup.d/setup-loglevel.sh, opensuse-tomcat-jre11-juli-image/src/main/docker/startup.d/setup-tomcat-ssl-cert.sh, opensuse-tomcat-jre11-juli-image/src/test/resources/test.html, pom.xml
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=868108
=> US868108: Update Copyright statements to 2024

opensuse-tomcat-jre11-juli-image/src/main/docker/Dockerfile
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=887056
=> US887056: Download tomcat package during build

README.md, opensuse-tomcat-jre11-image/src/main/docker/Dockerfile, opensuse-tomcat-jre11-juli-image/src/main/docker/Dockerfile, release-notes-2.13.0.md
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=889116
=> US889116: Replace gosu with su-exec

opensuse-tomcat-jre11-image/pom.xml, opensuse-tomcat-jre11-image/src/main/docker/Dockerfile, opensuse-tomcat-jre11-juli-image/src/main/docker/Dockerfile, pom.xml
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=888096
=> US888096: Use docker image version management plugin

pom.xml, release-notes-2.15.0.md
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=920085
=> US920085: Release preparation

pom.xml, release-notes-2.16.0.md
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=977107
=> US977107: Release preparation

opensuse-tomcat-jre11-juli-image/src/main/docker/Dockerfile, pom.xml, release-notes-2.17.0.md
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=1000036
=> US1000036: Release preparation

pom.xml, release-notes-2.17.2.md
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=1011076
=> US1011076: Release preparation
